version: "3.9"
services: 
  crnn:
    build: 
      context: .
    image: kuangda/nvidia-pytorch
    environment: 
      - ROOT=TRUE
      - PASSWORD=my-pwd
      - DISABLE_AUTH=true
    shm_size: '64gb'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes: 
      - .:/home/derek
