version: "3.9"
services: 
  crnn:
    build: .
    image: kuangda/crnn
    ports: 
      - "8888:8888"
    environment: 
      - ROOT=TRUE
      - PASSWORD=my-pwd
      - DISABLE_AUTH=true
    # volumes: 
      # - .:/home/rstudio